FactoryGirl.define do
  factory :character do
    size "MyString"
    klass "MyString"
    race "MyString"
    alignment "MyString"
    strength "MyString"
    dexterity "MyString"
    intelligence "MyString"
    wisdom "MyString"
    charisma "MyString"
    constitution "MyString"
    hp "MyString"
    ac "MyString"
    initiative "MyString"
    speed "MyString"
    vision "MyString"
    acrobatics "MyString"
    animal_handling "MyString"
    arcana "MyString"
    arcana "MyString"
    athletics "MyString"
    deception "MyString"
    history "MyString"
    insight "MyString"
    intimidation "MyString"
    investigation "MyString"
    medicine "MyString"
    nature "MyString"
    perception "MyString"
    performance "MyString"
    persuasion "MyString"
    religion "MyString"
    sleight_of_hand "MyString"
    stealth "MyString"
    survival "MyString"
  end
end
